spring:
  application:
    name: drill-questions
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}?connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health
